-- BLANK - NO FUNCTIONS YET
--INSERT INTO root.vv_test_table (id,info,normal_col,update_col,ignore_col,v_valid_from,v_valid_to,v_deleted,v_changed_by) VALUES (1,'some info','init_normal','init_update','init_ignore',TIMESTAMPTZ '2020-12-07 21:00:00',TIMESTAMPTZ '9999-12-31 23:59:59','N','Me')
-- INIT
--INSERT INTO root.vv_test_table (id,info,normal_col,update_col,ignore_col) VALUES (1,'some info','init_normal','init_update','init_ignore')
-- ONLY NORMAL
--INSERT INTO root.vv_test_table (id,info,normal_col,update_col,ignore_col) VALUES (1,'some info','new_normal','init_update','init_ignore')
-- ONLY UPDATE
--INSERT INTO root.vv_test_table (id,info,normal_col,update_col,ignore_col) VALUES (1,'some info','init_normal','new_update','init_ignore')
-- ONLY IGNORE
--INSERT INTO root.vv_test_table (id,info,normal_col,update_col,ignore_col) VALUES (1,'some info','init_normal','init_update','new_ignore')
-- NORMAL + UPDATE
--INSERT INTO root.vv_test_table (id,info,normal_col,update_col,ignore_col) VALUES (1,'some info','new_normal','new_update','init_ignore')
-- NORMAL + IGNORE
--INSERT INTO root.vv_test_table (id,info,normal_col,update_col,ignore_col) VALUES (1,'some info','new_normal','init_update','new_ignore')
-- NORMAL + IGNORE + UPDATE
--INSERT INTO root.vv_test_table (id,info,normal_col,update_col,ignore_col) VALUES (1,'some info','new_normal','new_update','new_ignore')
-- IGNORE + UPDATE
--INSERT INTO root.vv_test_table (id,info,normal_col,update_col,ignore_col) VALUES (1,'some info','init_normal','new_update','new_ignore')